package com.balloon.entity;

public class AuthKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_key.id
     *
     * @mbggenerated
     */
    private Double id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_key.auth_key
     *
     * @mbggenerated
     */
    private String authKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column auth_key.account
     *
     * @mbggenerated
     */
    private String account;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_key.id
     *
     * @return the value of auth_key.id
     *
     * @mbggenerated
     */
    public Double getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_key.id
     *
     * @param id the value for auth_key.id
     *
     * @mbggenerated
     */
    public void setId(Double id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_key.auth_key
     *
     * @return the value of auth_key.auth_key
     *
     * @mbggenerated
     */
    public String getAuthKey() {
        return authKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_key.auth_key
     *
     * @param authKey the value for auth_key.auth_key
     *
     * @mbggenerated
     */
    public void setAuthKey(String authKey) {
        this.authKey = authKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column auth_key.account
     *
     * @return the value of auth_key.account
     *
     * @mbggenerated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column auth_key.account
     *
     * @param account the value for auth_key.account
     *
     * @mbggenerated
     */
    public void setAccount(String account) {
        this.account = account;
    }
}