package com.balloon.entity;

import java.util.Date;

/**
 * 获取首页微博列表
 * @author Administrator
 *
 */
public class HomePageData {
    @Override
	public String toString() {
		return "HomePageData [id=" + id + ", mediaurl=" + mediaurl + ", content=" + content + ", mediatype=" + mediatype
				+ ", name=" + name + ", createdata=" + createdata + ", headsculptureurl=" + headsculptureurl
				+ ", handsettype=" + handsettype + ", sharenum=" + sharenum + ", commentnum=" + commentnum
				+ ", praisenum=" + praisenum + "]";
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.mediaUrl
     *
     * @mbggenerated
     */
    private String mediaurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.mediaType
     *
     * @mbggenerated
     */
    private Integer mediatype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.createData
     *
     * @mbggenerated
     */
    private Date createdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.headSculptureUrl
     *
     * @mbggenerated
     */
    private String headsculptureurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.handSetType
     *
     * @mbggenerated
     */
    private Integer handsettype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.shareNum
     *
     * @mbggenerated
     */
    private Integer sharenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.commentNum
     *
     * @mbggenerated
     */
    private Integer commentnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column home_page_data.praiseNum
     *
     * @mbggenerated
     */
    private Integer praisenum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.id
     *
     * @return the value of home_page_data.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.id
     *
     * @param id the value for home_page_data.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.mediaUrl
     *
     * @return the value of home_page_data.mediaUrl
     *
     * @mbggenerated
     */
    public String getMediaurl() {
        return mediaurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.mediaUrl
     *
     * @param mediaurl the value for home_page_data.mediaUrl
     *
     * @mbggenerated
     */
    public void setMediaurl(String mediaurl) {
        this.mediaurl = mediaurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.content
     *
     * @return the value of home_page_data.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.content
     *
     * @param content the value for home_page_data.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.mediaType
     *
     * @return the value of home_page_data.mediaType
     *
     * @mbggenerated
     */
    public Integer getMediatype() {
        return mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.mediaType
     *
     * @param mediatype the value for home_page_data.mediaType
     *
     * @mbggenerated
     */
    public void setMediatype(Integer mediatype) {
        this.mediatype = mediatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.name
     *
     * @return the value of home_page_data.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.name
     *
     * @param name the value for home_page_data.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.createData
     *
     * @return the value of home_page_data.createData
     *
     * @mbggenerated
     */
    public Date getCreatedata() {
        return createdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.createData
     *
     * @param createdata the value for home_page_data.createData
     *
     * @mbggenerated
     */
    public void setCreatedata(Date createdata) {
        this.createdata = createdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.headSculptureUrl
     *
     * @return the value of home_page_data.headSculptureUrl
     *
     * @mbggenerated
     */
    public String getHeadsculptureurl() {
        return headsculptureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.headSculptureUrl
     *
     * @param headsculptureurl the value for home_page_data.headSculptureUrl
     *
     * @mbggenerated
     */
    public void setHeadsculptureurl(String headsculptureurl) {
        this.headsculptureurl = headsculptureurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.handSetType
     *
     * @return the value of home_page_data.handSetType
     *
     * @mbggenerated
     */
    public Integer getHandsettype() {
        return handsettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.handSetType
     *
     * @param handsettype the value for home_page_data.handSetType
     *
     * @mbggenerated
     */
    public void setHandsettype(Integer handsettype) {
        this.handsettype = handsettype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.shareNum
     *
     * @return the value of home_page_data.shareNum
     *
     * @mbggenerated
     */
    public Integer getSharenum() {
        return sharenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.shareNum
     *
     * @param sharenum the value for home_page_data.shareNum
     *
     * @mbggenerated
     */
    public void setSharenum(Integer sharenum) {
        this.sharenum = sharenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.commentNum
     *
     * @return the value of home_page_data.commentNum
     *
     * @mbggenerated
     */
    public Integer getCommentnum() {
        return commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.commentNum
     *
     * @param commentnum the value for home_page_data.commentNum
     *
     * @mbggenerated
     */
    public void setCommentnum(Integer commentnum) {
        this.commentnum = commentnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column home_page_data.praiseNum
     *
     * @return the value of home_page_data.praiseNum
     *
     * @mbggenerated
     */
    public Integer getPraisenum() {
        return praisenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column home_page_data.praiseNum
     *
     * @param praisenum the value for home_page_data.praiseNum
     *
     * @mbggenerated
     */
    public void setPraisenum(Integer praisenum) {
        this.praisenum = praisenum;
    }
}