package com.balloon.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.balloon.entity.Account;

public interface AccountMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Float id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account
	 *
	 * @mbggenerated
	 */
	int insert(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account
	 *
	 * @mbggenerated
	 */
	int insertSelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account
	 *
	 * @mbggenerated
	 */
	Account selectByPrimaryKey(Float id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Account record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table account
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Account record);

	/**
	 * 根据账号密码登陆
	 * 
	 * @param record
	 * @return
	 */
	Account selectByAccountAndPsd(Account record);

	/**
	 * 查看账户是否存在
	 * 
	 * @param record
	 * @return
	 */
	Account selectByAccount(Account record);

}