package com.balloon.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.balloon.entity.AuthKey;

public interface AuthKeyMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table auth_key
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Double id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table auth_key
	 *
	 * @mbggenerated
	 */
	int insert(AuthKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table auth_key
	 *
	 * @mbggenerated
	 */
	int insertSelective(AuthKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table auth_key
	 *
	 * @mbggenerated
	 */
	AuthKey selectByPrimaryKey(Double id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table auth_key
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(AuthKey record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table auth_key
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AuthKey record);
}