package com.balloon.mapper;

import java.util.List;

import com.balloon.entity.HomePageData;

public interface HomePageDataMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_data
     *
     * @mbggenerated
     */
    int insert(HomePageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_data
     *
     * @mbggenerated
     */
    int insertSelective(HomePageData record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_data
     *
     * @mbggenerated
     */
    HomePageData selectByPrimaryKey(Integer id);



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HomePageData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table home_page_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HomePageData record);
    
    
    List<HomePageData> selectByGroup(Integer id);
}